import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { formatDate } from "@/lib/utils";
import { PrintButton } from "@/components/forms";

export default async function PrintCertificatePage({
  params,
}: {
  params: Promise<{ code: string }>;
}) {
  const { code } = await params;
  const certificate = await prisma.certificate.findUnique({
    where: { certificateNo: decodeURIComponent(code) },
    include: {
      instrument: { include: { owner: true } },
      application: { include: { inspection: true } },
    },
  });
  if (!certificate) notFound();

  return (
    <div className="min-h-screen bg-white p-10 print:p-0">
      <div className="mx-auto max-w-[800px] border-2 border-[var(--navy)] p-8">
        <p className="text-center text-xs uppercase tracking-[0.25em]">
          Government of Telangana · Legal Metrology Department
        </p>
        <h1 className="font-display text-3xl text-center mt-2">Verification Certificate</h1>
        <p className="text-center text-sm mt-1">
          Issued under the Legal Metrology Act, 2009 and the Legal Metrology (General) Rules, 2011
        </p>
        <div className="grid grid-cols-[1fr_160px] gap-6 mt-8 text-sm">
          <table className="w-full">
            <tbody>
              {[
                ["Certificate no.", certificate.certificateNo],
                ["Application no.", certificate.application.applicationNo],
                ["Instrument", `${certificate.instrument.make} ${certificate.instrument.model}`],
                ["Serial number", certificate.instrument.serialNumber],
                ["Category / class", `${certificate.instrument.category} / ${certificate.instrument.accuracyClass}`],
                ["Capacity", certificate.instrument.capacity],
                ["User", certificate.instrument.owner.name],
                ["Premises", certificate.instrument.premisesName],
                ["Address", certificate.instrument.address],
                ["Issued on", formatDate(certificate.issuedAt)],
                ["Valid until", formatDate(certificate.validUntil)],
                ["Inspection result", certificate.application.inspection?.result || "PASS"],
                ["Observed error", certificate.application.inspection?.observedError || "—"],
              ].map(([k, v]) => (
                <tr key={k} className="border-b">
                  <td className="py-2 text-[var(--muted)] w-40">{k}</td>
                  <td className="py-2 font-medium">{v}</td>
                </tr>
              ))}
            </tbody>
          </table>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={certificate.qrPayload} alt="QR" className="w-40 h-40" />
        </div>
        <p className="mt-8 text-[11px] font-mono break-all">Hash: {certificate.integrityHash}</p>
        <p className="mt-6 text-xs text-[var(--muted)]">
          This prototype certificate is digitally generated by MaapSetu. In production it would be
          digitally signed (eSign) and optionally pushed to DigiLocker / e-Maap.
        </p>
        <PrintButton />
      </div>
    </div>
  );
}
